name: Build and Release 

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo at tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install uv
        run: pip install uv
        timeout-minutes: 5

      - name: Install PyInstaller
        run: pip install pyinstaller
        timeout-minutes: 5

      - name: Install dependencies with uv
        run: uv sync
        timeout-minutes: 10

      - name: Build executable with PyInstaller (inside uv env)
        run: uv run ./build.bat
        timeout-minutes: 15

      - name: Install Inno Setup
        shell: pwsh
        run: choco install innosetup -y
        timeout-minutes: 10

      - name: Build installer with Inno Setup
        run: ISCC.exe setup.iss
        timeout-minutes: 10

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: QuikCapInstaller
          path: Output/QuikCapInstaller.exe

      - name: Create Release and Upload Installer
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          files: ./Output/QuikCapInstaller.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
