name: Build and Publish Installer

on:
  workflow_dispatch: # Manual trigger, can add tags or branches if desired
  # Example to also trigger on tags:
  # push:
  #   tags:
  #     - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install uv
        run: pip install uv
        timeout-minutes: 5

      - name: Install dependencies with uv
        run: uv sync
        timeout-minutes: 10

      - name: Build executable with PyInstaller (inside uv env)
        run: uv run ./build.bat
        timeout-minutes: 15

      - name: Install Chocolatey
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        timeout-minutes: 10

      - name: Install Inno Setup
        shell: pwsh
        run: choco install innosetup -y
        timeout-minutes: 10

      - name: Build installer with Inno Setup
        run: ISCC.exe setup.is
        timeout-minutes: 10

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: QuikCapInstaller
          path: Output/QuikCapInstaller.exe

      - name: Create Release and Upload Installer
        uses: softprops/action-gh-release@v1
        with:
          files: ./Output/QuikCapInstaller.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
